name: Mirror to GitLab

on: [push, delete, create]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0' # Fetch all history for all tags and branches
    - name: Mirror to GitLab
      env:
        GITLAB_SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H gitlab.ideatolife.me >> ~/.ssh/known_hosts
        
        # Configure Git
        git config --global user.email "syed.salman@ideatolife.me"
        git config --global user.name "syed.salman"

        # Push to GitLab
        git remote add gitlab git@gitlab.ideatolife.me:syed.salman/disc-frontend.git
        git push gitlab main --force-with-lease
   

